# Generated by Django 4.2.4 on 2023-08-23 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_games_teams_playergames_games_awayteamid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='awayTeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.teams'),
        ),
        migrations.AlterField(
            model_name='games',
            name='homeTeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.teams'),
        ),
    ]
